import 'dart:math';

/// 各语言男主角姓名池（每个语言 100 个，硬编码，均为古代/现代/未来都不违和的经典通用名）。
/// key 与 StorageService.getLanguage() 的代码一致（zh/zh-TW/yue/en/es/fr/de/pt/ja/ko）。
const Map<String, List<String>> kMalePlayerNames = {
  'zh': [
        '陆一鸣', '顾北辰', '沈砚舟', '江临风', '傅言之', '程墨白', '许之衡', '苏怀瑾',
        '韩修远', '秦问天', '林晚舟', '陆沉舟', '顾长歌', '沈惊鸿', '江寻野', '傅清越',
        '程渡川', '许清晏', '苏聿修', '韩之州', '秦珩', '林则安', '陆昭', '顾砚',
        '沈辞', '江白', '傅野', '程曦', '许念', '苏屿', '韩川', '秦越',
        '林叙', '陆言', '顾野', '沈止', '江阔', '傅明', '程言', '许述',
        '苏衡', '韩让', '秦朗', '林予', '陆则', '顾怀', '沈聿', '江停',
        '傅声', '程年', '许迟', '苏陌', '韩青', '秦初', '林舟', '陆衡',
        '顾驰', '沈曦', '江赫', '傅钺', '许凛', '苏焯', '林帆', '白景明',
        '周砚', '陈默', '曹岳', '程澈', '韩阳', '秦野', '陆明', '顾言',
        '沈岩', '江行', '傅元', '许峻', '苏淮', '韩泽', '秦凯', '林远',
        '陆时', '顾平', '沈岚', '江鸣', '傅川', '许渊', '苏汀', '韩霖',
        '秦书', '林岫', '陆臣', '顾城', '沈澈', '江舟', '傅棠', '许岑',
        '苏然', '韩序', '秦岳', '林朗',
  ],
  'zh-TW': [
        '陸一鳴', '顧北辰', '沈硯舟', '江臨風', '傅言之', '程墨白', '許之衡', '蘇懷瑾',
        '韓修遠', '秦問天', '林晚舟', '陸沉舟', '顧長歌', '沈驚鴻', '江尋野', '傅清越',
        '程渡川', '許清晏', '蘇聿修', '韓之州', '秦珩', '林則安', '陸昭', '顧硯',
        '沈辭', '江白', '傅野', '程曦', '許念', '蘇嶼', '韓川', '秦越',
        '林敘', '陸言', '顧野', '沈止', '江闊', '傅明', '程言', '許述',
        '蘇衡', '韓讓', '秦朗', '林予', '陸則', '顧懷', '沈聿', '江停',
        '傅聲', '程年', '許遲', '蘇陌', '韓青', '秦初', '林舟', '陸衡',
        '顧馳', '沈曦', '江赫', '傅鉞', '許凜', '蘇焯', '林帆', '白景明',
        '周硯', '陳默', '曹岳', '程澈', '韓陽', '秦野', '陸明', '顧言',
        '沈巖', '江行', '傅元', '許峻', '蘇淮', '韓澤', '秦凱', '林遠',
        '陸時', '顧平', '沈嵐', '江鳴', '傅川', '許淵', '蘇汀', '韓霖',
        '秦書', '林岫', '陸臣', '顧城', '沈澈', '江舟', '傅棠', '許岑',
        '蘇然', '韓序', '秦岳', '林朗',
  ],
  'yue': [
        '陸一鳴', '陳國樑', '李俊賢', '張嘉豪', '黃志偉', '吳俊傑', '劉國豪', '鄭家俊',
        '何文軒', '周嘉明', '馬俊朗', '羅國輝', '梁文傑', '謝志豪', '林嘉俊', '郭俊賢',
        '余家輝', '譚國豪', '曾俊朗', '蔡嘉豪', '潘文軒', '楊國輝', '杜俊傑', '葉嘉俊',
        '彭文豪', '方俊賢', '黎國豪', '古嘉明', '邵俊傑', '翁志豪', '萬嘉俊', '麥俊賢',
        '簡國豪', '龔文軒', '嚴俊傑', '雷嘉豪', '陸嘉輝', '關俊朗', '蕭國豪', '莊志賢',
        '尹嘉俊', '范文豪', '勞俊賢', '湯國豪', '莫嘉傑', '石俊朗', '陸嘉俊', '陳俊賢',
        '李國輝', '張俊豪', '黃嘉文', '吳國豪', '劉俊朗', '鄭嘉輝', '何俊賢', '周國豪',
        '馬嘉俊', '羅俊豪', '梁國輝', '謝嘉賢', '林俊豪', '郭嘉輝', '余文軒', '譚俊豪',
        '曾嘉賢', '蔡國輝', '潘俊賢', '楊嘉豪', '杜俊賢', '葉文軒', '彭俊豪', '方國輝',
        '黎俊賢', '古嘉輝', '邵文軒', '翁俊豪', '萬國輝', '麥嘉俊', '簡文軒', '龔嘉豪',
        '嚴俊賢', '雷國豪', '陸文軒', '關嘉俊', '蕭俊豪', '莊國輝', '尹俊賢', '范嘉豪',
        '勞文軒', '湯俊豪', '陳嘉豪', '李浩然', '張子軒', '黃俊傑', '劉俊賢', '鄭嘉豪',
        '莫國輝', '石俊賢', '吳國樑', '何國良',
  ],
  'en': [
        'Aaron', 'Adam', 'Alan', 'Albert', 'Alexander', 'Alfred', 'Andrew', 'Anthony',
        'Archibald', 'Arthur', 'Barry', 'Benjamin', 'Bernard', 'Carl', 'Cecil', 'Charles',
        'Christopher', 'Clarence', 'Clifford', 'Colin', 'Conrad', 'Cornelius', 'Daniel', 'David',
        'Dennis', 'Donald', 'Douglas', 'Duncan', 'Edgar', 'Edmund', 'Edward', 'Edwin',
        'Eli', 'Elijah', 'Emanuel', 'Eric', 'Ernest', 'Eugene', 'Felix', 'Ferdinand',
        'Francis', 'Frank', 'Frederick', 'Gabriel', 'Geoffrey', 'George', 'Gerald', 'Gilbert',
        'Gordon', 'Graham', 'Gregory', 'Harold', 'Harvey', 'Henry', 'Herbert', 'Herman',
        'Howard', 'Hugh', 'Isaac', 'Jack', 'Jacob', 'James', 'Jasper', 'Jeremiah',
        'Jerome', 'John', 'Jonathan', 'Joseph', 'Joshua', 'Julian', 'Keith', 'Kenneth',
        'Kevin', 'Lawrence', 'Leonard', 'Lewis', 'Lionel', 'Louis', 'Luke', 'Malcolm',
        'Marcus', 'Mark', 'Martin', 'Matthew', 'Maurice', 'Michael', 'Miles', 'Morgan',
        'Nathaniel', 'Neil', 'Nicholas', 'Nigel', 'Noah', 'Norman', 'Oliver', 'Oscar',
        'Owen', 'Patrick', 'Paul', 'Peter',
  ],
  'es': [
        'Alejandro', 'Carlos', 'Diego', 'Fernando', 'Javier', 'Luis', 'Miguel', 'Pablo',
        'Rafael', 'Ricardo', 'Rodrigo', 'Santiago', 'Álvaro', 'Antonio', 'Arturo', 'Bruno',
        'César', 'Cristian', 'Daniel', 'David', 'Eduardo', 'Emilio', 'Enrique', 'Esteban',
        'Felipe', 'Francisco', 'Gabriel', 'Gonzalo', 'Guillermo', 'Gustavo', 'Héctor', 'Hugo',
        'Ignacio', 'Iván', 'Jaime', 'Joaquín', 'Jorge', 'José', 'Juan', 'Lorenzo',
        'Manuel', 'Marcos', 'Mario', 'Martín', 'Matías', 'Mauricio', 'Nicolás', 'Óscar',
        'Pedro', 'Ramón', 'Rubén', 'Salvador', 'Samuel', 'Sebastián', 'Tomás', 'Víctor',
        'Vicente', 'Alberto', 'Andrés', 'Ángel', 'Benjamín', 'Camilo', 'Damián', 'Emiliano',
        'Ernesto', 'Fabián', 'Federico', 'Germán', 'Julián', 'Leandro', 'Luciano', 'Mateo',
        'Néstor', 'Patricio', 'Ramiro', 'Sergio', 'Simón', 'Teodoro', 'Valentín', 'Adrián',
        'Alfonso', 'Anselmo', 'Alonso', 'Efraín', 'Humberto', 'Nicanor', 'Orlando', 'Reynaldo',
        'Telmo', 'Ezequiel', 'Gael', 'Isidro', 'León', 'Narciso', 'Onofre', 'Pío',
        'Sabino', 'Ubaldo', 'Vidal', 'Zacarías',
  ],
  'fr': [
        'Louis', 'Arthur', 'Gabriel', 'Jules', 'Adam', 'Raphaël', 'Lucas', 'Hugo',
        'Léo', 'Nathan', 'Tom', 'Evan', 'Théo', 'Augustin', 'Antoine', 'Bastien',
        'Clément', 'Damien', 'Édouard', 'Émile', 'Fabien', 'Félix', 'Florian', 'François',
        'Gaël', 'Guillaume', 'Henri', 'Jean', 'Julien', 'Laurent', 'Marc', 'Mathis',
        'Maxime', 'Nicolas', 'Olivier', 'Paul', 'Philippe', 'Pierre', 'Quentin', 'Rémi',
        'Romain', 'Samuel', 'Simon', 'Stéphane', 'Thibault', 'Valentin', 'Victor', 'Vincent',
        'Yann', 'Alexandre', 'Alban', 'Amaury', 'Armand', 'Axel', 'Baptiste', 'Benjamin',
        'Charles', 'Corentin', 'Cyrille', 'Dorian', 'Étienne', 'Geoffroy', 'Jérôme', 'Loïc',
        'Ludovic', 'Mathieu', 'Maxence', 'Michel', 'Pascal', 'Robin', 'Sébastien', 'Sylvain',
        'Tanguy', 'Thierry', 'Timothée', 'Virgile', 'Yohan', 'Achille', 'Adrien', 'Benoît',
        'Auguste', 'Basile', 'Cyprien', 'Émeric', 'Flavien', 'Honoré', 'Léandre', 'Marius',
        'Albin', 'Anatole', 'Clovis', 'Éloi', 'Firmin', 'Norbert', 'Prosper', 'Didier',
        'Hilaire', 'René', 'Ambroise', 'Aubin',
  ],
  'de': [
        'Leon', 'Lukas', 'Finn', 'Jonas', 'Noah', 'Paul', 'Luca', 'Felix',
        'Elias', 'Luis', 'Maximilian', 'Henry', 'Julian', 'Emil', 'Anton', 'Theo',
        'Moritz', 'David', 'Samuel', 'Alexander', 'Ben', 'Carl', 'Christian', 'Daniel',
        'Erik', 'Fabian', 'Florian', 'Frederick', 'Gabriel', 'Georg', 'Hannes', 'Jakob',
        'Jan', 'Jasper', 'Jens', 'Johann', 'Josef', 'Julius', 'Karl', 'Konstantin',
        'Lars', 'Lennard', 'Lorenz', 'Magnus', 'Manuel', 'Marcel', 'Marco', 'Marius',
        'Markus', 'Martin', 'Matthias', 'Max', 'Michael', 'Niklas', 'Nils', 'Oskar',
        'Otto', 'Patrick', 'Peter', 'Philipp', 'Raphael', 'Robert', 'Robin', 'Rudolf',
        'Sebastian', 'Stefan', 'Timo', 'Tobias', 'Tom', 'Valentin', 'Vincent', 'Wilhelm',
        'Wolfgang', 'Andreas', 'Armin', 'Bastian', 'Clemens', 'Dominik', 'Eduard', 'Ferdinand',
        'Arne', 'Benedikt', 'Caspar', 'Ewald', 'Gunnar', 'Holger', 'Jannik', 'Kurt',
        'Lothar', 'Ole', 'Peer', 'Ralf', 'Uwe', 'Dietrich', 'Emmerich', 'Folker',
        'Gerold', 'Hartmut', 'Immo', 'Jochen',
  ],
  'pt': [
        'João', 'Miguel', 'Arthur', 'Gabriel', 'Heitor', 'Davi', 'Bernardo', 'Samuel',
        'Pedro', 'Enzo', 'Lorenzo', 'Matheus', 'Rafael', 'Lucas', 'Guilherme', 'Gustavo',
        'Henrique', 'Luiz', 'Felipe', 'Leonardo', 'Vicente', 'Antônio', 'Caio', 'Daniel',
        'Eduardo', 'Francisco', 'Isaac', 'Joaquim', 'Leandro', 'Manuel', 'Marcelo', 'Mário',
        'Nicolau', 'Otávio', 'Paulo', 'Rogério', 'Rodrigo', 'Thiago', 'Vitor', 'André',
        'Bruno', 'Carlos', 'César', 'Cláudio', 'Cristiano', 'Douglas', 'Fábio', 'Fernando',
        'Flávio', 'Geraldo', 'Gilberto', 'Hélio', 'Humberto', 'Jader', 'Jairo', 'Jorge',
        'Josué', 'Luan', 'Luciano', 'Marcos', 'Maurício', 'Murilo', 'Nelson', 'Nuno',
        'Ricardo', 'Roberto', 'Rui', 'Sérgio', 'Valter', 'Artur', 'Baltasar', 'Dinis',
        'Egas', 'Filipe', 'Gaspar', 'Inácio', 'Justino', 'Lisandro', 'Plínio', 'Teófilo',
        'Afonso', 'Caetano', 'Estevão', 'Firmino', 'Ivo', 'Norberto', 'Salomão', 'Urbano',
        'Zacarias', 'Almir', 'Adelino', 'Adriano', 'Alípio', 'Amâncio', 'Aníbal', 'Bartolomeu',
        'Belchior', 'Bento', 'Cipriano', 'Custódio',
  ],
  'ja': [
        '隆', '博', '誠', '守', '大介', '一郎', '幸', '剛',
        '健', '直', '真', '和', '勝', '明', '修', '正',
        '孝', '毅', '亮', '純', '信', '宏', '仁', '謙',
        '崇', '進', '昭', '敏', '敬', '賢', '卓', '亨',
        '清', '義', '豊', '朗', '光', '輝', '広', '政',
        '達', '篤', '淳', '秀', '彰', '利', '正人', '裕',
        '洋', '恒', '晃', '昌', '規', '靖', '康', '和夫',
        '信一', '一正', '健一', '博文', '正和', '忠志', '勇人', '誠一',
        '太郎', '次郎', '三郎', '敬一', '明宏', '尚志', '亮介', '和也',
        '剛志', '大輔', '直樹', '祐介', '拓也', '大輝', '悠人', '颯人',
        '洋介', '誠治', '正雄', '和彦', '光一', '健太郎', '秀樹', '哲也',
        '謙一', '信之', '宏之', '篤志', '泰三', '清人', '研二', '雅也',
        '孝太郎', '正信', '宗一郎', '崇文',
  ],
  'ko': [
        '민수', '영호', '동욱', '상현', '현우', '재현', '진우', '용준',
        '성민', '준호', '민석', '승현', '태민', '지환', '규현', '건호',
        '윤호', '서진', '도윤', '우빈', '현수', '정훈', '승호', '재민',
        '태영', '민규', '준영', '상우', '광수', '동민', '성호', '영민',
        '진호', '현석', '우성', '태호', '민우', '지성', '강호', '동진',
        '경수', '병철', '상민', '선호', '성진', '수현', '승민', '시진',
        '우진', '은호', '이현', '정현', '진수', '찬호', '태현', '표민',
        '하성', '한결', '현민', '형준', '기범', '남준', '대현', '범수',
        '석현', '영준', '오성', '원호', '유진', '정민', '주호', '지훈',
        '찬민', '태성', '호준', '준수', '승찬', '민호', '진혁', '재호',
        '가온', '준성', '도하', '규원', '재이', '세진', '찬우', '하늘',
        '이든', '로운', '서우', '태오', '해온', '예건', '지혁', '유찬',
        '시안', '다온', '재원', '은성',
  ],
};

/// 按语言随机取一个男主角名字；未知语言回退简体中文池。
String randomMalePlayerName(String language) {
  final pool = kMalePlayerNames[language];
  final list = (pool != null && pool.isNotEmpty) ? pool : kMalePlayerNames['zh']!;
  return list[Random().nextInt(list.length)];
}
